---
- name: Configure Sonatype Nexus
  hosts: nexus
  become: true
  vars:
    directories:
      - /nexus-ebs/nexus
      - /nexus-ebs/sonatype-work
  
  tasks:
    - name: make file system for ebs
      filesystem:
        fstype: ext4
        force: no
        dev: /dev/xvdf
   
    - name: mount the ebs 
      mount:
        path: /nexus-ebs
        src: /dev/xvdf
        state: mounted
        fstype: ext4

    - name: Update apt cache
      apt:
        update_cache: yes
      
    - name: Install OpenJDK 17
      apt:
        name: openjdk-17-jdk
        state: present
    
    - name: Download Nexus on controller
      get_url:
        url: "https://download.sonatype.com/nexus/3/nexus-3.83.2-01-linux-x86_64.tar.gz"
        dest: /nexus-ebs/

    - name: unarchive files
      unarchive:
        src: /nexus-ebs/nexus-3.83.2-01-linux-x86_64.tar.gz
        dest: /nexus-ebs/
        remote_src: yes
    
    - name: change the name of the extracted file
      script: ./script2.sh

    - name: add nexus user
      user:
        name: nexus
    
    - name: give nexus user permissions
      lineinfile: 
        path: /etc/sudoers
        line: "nexus ALL=(ALL) NOPASSWD: ALL"
    
    - name: change ownership of nexus directories to nexus user
      file:
        path: "{{item}}"
        owner: nexus
        group: nexus
        recurse: yes
      loop: "{{directories}}"
    
    - name: Ensure Nexus service runs as nexus user
      lineinfile:
        path: /nexus-ebs/nexus/bin/nexus
        regexp: '^#?run_as_user='
        line: 'run_as_user="nexus"'
        state: present

    - name: Increase the nexus JVM heap size
      lineinfile: 
        path: /nexus-ebs/nexus/bin/nexus.vmoptions
        regexp: "^-XX:MaxDirectMemorySize=*"
        line: "-XX:MaxDirectMemorySize=2703m"
   
    - name: Increase the nexus JVM heap size another modify
      lineinfile: 
        path: /nexus-ebs/nexus/bin/nexus.vmoptions
        regexp: "$-Djava.net.preferIPv4Stack=*"
        line: "-Djava.net.preferIPv4Stack=true"

    - name: change nexus default
      command: sudo sed -i 's|nexus-work=.*|nexus-work=/nexus-ebs|' /nexus-ebs/nexus/etc/nexus-default.properties

    - name: Create Nexus systemd service
      copy:
        dest: /etc/systemd/system/nexus.service
        mode: '0644'
        content: |
          [Unit]
          Description=nexus service
          After=network.target

          [Service]
          Type=forking
          LimitNOFILE=65536
          ExecStart=/nexus-ebs/nexus/bin/nexus start
          ExecStop=/nexus-ebs/nexus/bin/nexus stop
          User=nexus
          Restart=on-abort

          [Install]
          WantedBy=multi-user.target

    - name: Reload systemd daemon
      command: systemctl daemon-reload

    - name: Enable Nexus service
      service:
        name: nexus
        enabled: yes

    - name: Start Nexus service
      service:
        name: nexus
        state: started

    - name: access throw internet
      command: ufw allow 8081/tcp